// Auto-generated by test_cov. Do not edit by hand.

import 'unit\usecases\auth_usecases_test.dart' as unit_usecases_auth_usecases_test;
import 'unit\view_models\auth_view_models_test.dart' as unit_view_models_auth_view_models_test;
import 'widget\mybutton_widget_test.dart' as widget_mybutton_widget_test;
import 'widget\mytextformfield_widget_test.dart' as widget_mytextformfield_widget_test;
import 'widget\smart_network_avatar_widget_test.dart' as widget_smart_network_avatar_widget_test;

void main() {
  widget_mybutton_widget_test.main();
  widget_mytextformfield_widget_test.main();
  widget_smart_network_avatar_widget_test.main();
  unit_usecases_auth_usecases_test.main();
  unit_view_models_auth_view_models_test.main();
}
